project/chemlab/__init__.py
import os
import random
import string
from datetime import datetime
import ssl

from flask import Blueprint, render_template, redirect, url_for, session, request
from flask_dance.contrib.google import make_google_blueprint, google
from flask_dance.contrib.facebook import make_facebook_blueprint, facebook
from flask_dance.contrib.linkedin import make_linkedin_blueprint, linkedin
from firebase_admin import credentials, firestore, auth, initialize_app

chemlab_blueprint = Blueprint('chemlab', __name__)
chemlab_blueprint.secret_key = "your_secret_key"


google_client_id = os.environ['GOOGLE_CLIENT_ID']
google_client_secret = os.environ['GOOGLE_CLIENT_SECRET']

facebook_client_id = os.environ['FACEBOOK_CLIENT_ID']
facebook_client_secret = os.environ['FACEBOOK_CLIENT_SECRET']

linkedin_client_id = os.environ['LINKEDIN_CLIENT_ID']
linkedin_client_secret = os.environ['LINKEDIN_CLIENT_SECRET']

firebase_credentials = {
    "type": "service_account",
    "project_id": os.environ.get('FIREBASE_PROJECT_ID'),
    "private_key_id": os.environ.get('PRIVATE_KEY_ID'),
    "private_key": os.environ.get('FIREBASE_PRIVATE_KEY').replace('\\n', '\n'),
    "client_email": os.environ.get('FIREBASE_CLIENT_EMAIL'),
    "client_id": os.environ.get('CLIENT_ID'),
    "auth_uri": os.environ.get('AUTH_URI'),
    "token_uri": os.environ.get('TOKEN_URI'),
    "auth_provider_x509_cert_url": os.environ.get('AUTH_PROVIDER_X509_CERT_URL'),
    "client_x509_cert_url": os.environ.get('CLIENT_X509_CERT_URL')
}

initialize_app(credentials.Certificate(firebase_credentials))

db = firestore.client()

google_blueprint = make_google_blueprint(
    client_id=google_client_id,
    client_secret=google_client_secret,
    scope=["https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email",
           "openid"],
    redirect_to="google_callback"
)
chemlab_blueprint.register_blueprint(google_blueprint, url_prefix="/login")

facebook_blueprint = make_facebook_blueprint(
    client_id=facebook_client_id,
    client_secret=facebook_client_secret,
    scope="email",
    redirect_to="facebook_callback"
)
chemlab_blueprint.register_blueprint(facebook_blueprint, url_prefix="/login")

linkedin_blueprint = make_linkedin_blueprint(
    client_id=linkedin_client_id,
    client_secret=linkedin_client_secret,
    scope=["r_emailaddress"],
    redirect_to="linkedin_callback"
)
chemlab_blueprint.register_blueprint(linkedin_blueprint, url_prefix="/login")


def load_users():
    users_ref = db.collection('users')
    users = {}
    docs = users_ref.get()
    for doc in docs:
        user_data = doc.to_dict()
        users[user_data['email']] = user_data
    return users


def validate_password(email, password):
    users = load_users()
    if email in users and users[email]["password"] == password:
        return True
    return False


def is_user_logged_in():
    return "user" in session


def get_questions():
    questions = []
    collection_ref = db.collection("questions_and_answers")
    query = collection_ref.order_by("question").select(["question"])

    for doc in query.stream():
        question = doc.to_dict()["question"]
        questions.append(question)

    return questions


def get_answers():
    answers = []
    collection_ref = db.collection("questions_and_answers")
    query = collection_ref.order_by("question").select(["answer"])

    for doc in query.stream():
        answer = doc.to_dict()["answer"]
        answers.append(answer)

    return answers


@chemlab_blueprint.route("/")
def index():
    if not is_user_logged_in():
        return redirect(url_for("chemlab.login"))

    questions = get_questions()
    answers = get_answers()
    zipped_questions = zip(questions, answers)

    return render_template("index.html", questions=zipped_questions)


@chemlab_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if is_user_logged_in():
        # If the user is already logged in, redirect to the index page
        return redirect(url_for("chemlab.index"))

    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        users_ref = db.collection("users")
        query = users_ref.where("email", "==", email).limit(1)
        users = query.get()

        if len(users) == 1:
            user_data = users[0].to_dict()
            stored_password = user_data["password"]
            if stored_password == password:
                session["user"] = email
                session["login_via"] = "email"
                # After successful login, redirect to the index page
                return redirect(url_for("chemlab.index"))

        error = "Invalid email or password"
        return render_template("login.html", error=error)

    # Instead of redirecting, just render the login template
    return render_template("login.html")






def save_user_answer_audit(user_email, answers):
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    closing_key = generate_closing_key()
    login_via = session.get("login_via")

    record = {
        "timestamp": timestamp,
        "user_email": user_email,
        "answers": answers,
        "closing_key": closing_key,
        "login_via": login_via
    }
    audit_ref = db.collection("user_answer_audit")
    audit_ref.add(record)


def generate_closing_key():
    letters_and_digits = string.ascii_letters + string.digits
    closing_key = ''.join(random.choice(letters_and_digits) for _ in range(10))
    return closing_key


@chemlab_blueprint.route("/submit", methods=["POST"])
def submit():
    if not is_user_logged_in():
        return redirect(url_for("chemlab.login"))

    answers = []
    for i in range(1, 10):
        answer = request.form.get(f"q{i}")
        answers.append(answer)

    save_user_answer_audit(session["user"], answers)

    return redirect(url_for("chemlab.index"))


@chemlab_blueprint.route("/logout", methods=["GET", "POST"])
def logout():
    session.clear()
    return redirect(url_for("chemlab.login"))


@chemlab_blueprint.route("/google-login")
def google_login():
    if not google.authorized:
        return redirect(url_for("chemlab.google.login"))
    return redirect(url_for("chemlab.index"))


@chemlab_blueprint.route("/signup", methods=["GET", "POST"])
def signup():
    if is_user_logged_in():
        return redirect(url_for("chemlab.index"))

    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        first_name = request.form.get("first_name")
        last_name = request.form.get("last_name")
        date_of_birth = request.form.get("date_of_birth")
        country = request.form.get("country")

        users_ref = db.collection("users")
        user_data = {
            "email": email,
            "password": password,
            "first_name": first_name,
            "last_name": last_name,
            "date_of_birth": date_of_birth,
            "country": country
        }
        users_ref.document(email).set(user_data)

        session["user"] = email
        return redirect(url_for("chemlab.index"))

    return render_template("signup.html")


@chemlab_blueprint.route("/google-login/callback")
def google_callback():
    if not google.authorized:
        return redirect(url_for("chemlab.google.login"))
    resp = google.get("/oauth2/v1/userinfo")
    session["user"] = resp.json()["email"]
    session["login_via"] = "google"
    return redirect(url_for("chemlab.index"))


@chemlab_blueprint.route("/facebook-login")
def facebook_login():
    if not facebook.authorized:
        return redirect(url_for("chemlab.facebook.login"))
    return redirect(url_for("chemlab.index"))


@chemlab_blueprint.route("/facebook-login/callback")
def facebook_callback():
    if not facebook.authorized:
        return redirect(url_for("chemlab.facebook.login"))
    user_info = facebook.get("/me?fields=email")
    session["user"] = user_info.json().get("email")
    session["login_via"] = "facebook"
    return redirect(url_for("chemlab.index"))


@chemlab_blueprint.route("/linkedin-login")
def linkedin_login():
    if not linkedin.authorized:
        return redirect(url_for("chemlab.linkedin.login"))
    return redirect(url_for("chemlab.index"))


@chemlab_blueprint.route("/linkedin-login/callback")
def linkedin_callback():
    if not linkedin.authorized:
        return redirect(url_for("chemlab.linkedin.login"))

    resp = linkedin.get("/v2/emailAddress?q=members&projection=(elements*(handle~))")
    if resp.ok:
        user_data = resp.json()
        email_address = user_data.get("emailAddress")
        session["user"] = email_address if email_address else "linkedin"
        session["login_via"] = "linkedin"
    else:
        return "Failed to retrieve user data from LinkedIn."

    return redirect(url_for("chemlab.index"))


@chemlab_blueprint.route("/save_user_key", methods=["POST"])
def save_user_key():
    if not is_user_logged_in():
        return redirect(url_for("chemlab.login"))

    user_email = session["user"]
    closing_key = request.json.get("closing_key")
    login_via = session.get("login_via")

    user_key_ref = db.collection("user_key")

    key_data = {
        "timestamp": firestore.SERVER_TIMESTAMP,
        "user_email": user_email,
        "closing_key": closing_key,
        "login_via": login_via
    }

    user_key_ref.add(key_data)

    return "User Key saved successfully"


@chemlab_blueprint.route("/save_user_answers", methods=["POST"])
def save_user_answers():
    if not is_user_logged_in():
        return redirect(url_for("chemlab.login"))

    user_email = session["user"]
    login_via = session.get("login_via")

    answers = request.json.get("answers")
    audit_ref = db.collection("user_answer_audit")

    doc_data = {
        "timestamp": firestore.SERVER_TIMESTAMP,
        "user_email": user_email,
        "answers": answers,
        "login_via": login_via
    }

project/recipes/__init__.py
"""
The `recipes` blueprint handles displaying recipes.
"""
from flask import Blueprint

recipes_blueprint = Blueprint('recipes', __name__, template_folder='templates')

from . import routes

project/recipes/routes.py
from . import recipes_blueprint
from flask import render_template, abort


breakfast_recipes_names = ['pancakes', 'acai_bowl', 'honey_bran_muffins', 'breakfast_scramble',
                           'pumpkin_donuts', 'waffles', 'omelette', 'chocolate_donuts', 'oatmeal',
                           'morning_glory_muffins', 'blueberry_smoothie_bowl']
dinner_recipes_names = ['steak_fajitas', 'ground_beef_tacos', 'pizza', 'sweet_fire_chicken', 'tri_tip',
                        'shredded_chicken', 'taquitos', 'red_lentil_chili']
baked_goods_recipes_names = ['bagels', 'french_bread', 'pitas', 'irish_soda_bread', 'soft_rolls',
                             'pizza_dough', 'pitas2', 'banana_bread']
side_dishes_recipes_names = ['sweet_potatoes', 'spanish_rice', 'jasmine_rice', 'fruit_salad']
dessert_recipes_names = ['brownies', 'chocolate_chip_cookies', 'linzer_cookies', 'sugar_cookies',
                         'flourless_chocolate_cake']
drink_recipes_names = ['berry_smoothie', 'chocolate_milk_shake', 'apple_cider_vinegar_drink']


@recipes_blueprint.route('/')
def recipes():
    return render_template('recipes/recipes.html',
                           number_of_breakfast_recipes=len(breakfast_recipes_names),
                           number_of_dinner_recipes=len(dinner_recipes_names),
                           number_of_baked_goods_recipes=len(baked_goods_recipes_names),
                           number_of_side_dishes_recipes=len(side_dishes_recipes_names),
                           number_of_dessert_recipes=len(dessert_recipes_names),
                           number_of_drink_recipes=len(drink_recipes_names))


@recipes_blueprint.route('/breakfast/')
def breakfast_recipes():
    return render_template('recipes/breakfast.html')


@recipes_blueprint.route('/breakfast/<recipe_name>/')
def breakfast_recipe(recipe_name):
    if recipe_name not in breakfast_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/dinner/')
def dinner_recipes():
    return render_template('recipes/dinner.html')


@recipes_blueprint.route('/dinner/<recipe_name>/')
def dinner_recipe(recipe_name):
    if recipe_name not in dinner_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/baked_goods/')
def baked_goods_recipes():
    return render_template('recipes/baked_goods.html')


@recipes_blueprint.route('/baked_goods/<recipe_name>/')
def baked_goods_recipe(recipe_name):
    if recipe_name not in baked_goods_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/side_dishes/')
def side_dishes_recipes():
    return render_template('recipes/side_dishes.html')


@recipes_blueprint.route('/side_dishes/<recipe_name>/')
def side_dishes_recipe(recipe_name):
    if recipe_name not in side_dishes_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/dessert/')
def dessert_recipes():
    return render_template('recipes/dessert.html')


@recipes_blueprint.route('/dessert/<recipe_name>/')
def dessert_recipe(recipe_name):
    if recipe_name not in dessert_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/drink/')
def drink_recipes():
    return render_template('recipes/drink.html')


@recipes_blueprint.route('/drink/<recipe_name>/')
def drink_recipe(recipe_name):
    if recipe_name not in drink_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')

project/recipes1/__init__.py
# recipes1/__init__.py
"""
The `recipes1` blueprint handles displaying recipes.
"""
from flask import Blueprint

recipes1_blueprint = Blueprint('recipes1', __name__, template_folder='templates')

# Import the routes module
from . import routes

# Rest of the code remains the same

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>My Kitchen Recipe App</title>

        <!-- Local CSS file for styling the application-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base_style.css') }}">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">

        <!-- Additional Styling -->
        {% block styling %}
        {% endblock %}
    </head>

    <body>
        <header>
            <h1>My Kitchen Recipes</h1>
            <nav>
                <ul>
                    <li class="nav__item"><a href="{{ url_for('recipes.recipes') }}" class="nav__link">Recipes</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.blog') }}" class="nav__link">Blog</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.about') }}" class="nav__link">About</a></li>
                    <li class="nav__item"><a href="{{ url_for('tweet.tweet') }}" class="nav__link">Tweet</a></li>
			  <li class="nav__item"><a href="{{ url_for('recipes1.recipes1_index') }}" class="nav__link">Mediterranean</a></li>
                </ul>
            </nav>
        </header>

        <main class="content">
            <!-- child template -->
            {% block content %}
            {% endblock %}
        </main>

        <footer>
            <p>Created by <a href="https://sajumulakkal.netlify.app/">Saju Mulakkal Joseph</a> (2022)</p>
        </footer>
    </body>
</html>

project/templates/blogpost.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blogpost_style.css') }}">
{% endblock %}

{% block content %}
<div class="blogpost-container card-overlay">
    <div class="blogpost__heading">
        {% block title %}
        {% endblock %}

        <h3>by Saju Mulakkal</h3>

        {% block date %}
        {% endblock %}
    </div>

    <div class="blogpost__image">
        {% block image %}
        {% endblock %}
    </div>

    <div class="blogpost__article">
        {% block article %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Chemistry Lab Closure</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>For Closing your Chemistry Lab, you need to complete the following questions. Once completed, a Closing Key will be generated. You can use that key to close your Laboratory.</h1>
    <form id="questionForm" action="/submit" method="post">
        <div id="questionContainer">
            {% for question, answer in questions %}
            <div class="question">
                <label for="q{{ loop.index }}">{{ question }}</label>
                <input type="text" id="q{{ loop.index }}" name="q{{ loop.index }}" required>
                <input type="hidden" id="a{{ loop.index }}" name="a{{ loop.index }}" value="{{ answer }}">
            </div>
            {% endfor %}
        </div>
        <div id="randomNumber" style="display: none;"></div>
        <button id="submitBtn" type="submit" class="btn">Submit</button>
    </form>

    <div class="logout">
        <form action="/logout" method="post">
            <button type="submit" class="btn">Logout</button>
        </form>
    </div>

    <script>
        document.getElementById("questionForm").addEventListener("submit", function(event) {
            event.preventDefault();

            const questions = document.querySelectorAll("input[type='text']");
            const answers = Array.from(questions).map(question => question.value.trim());
            const expectedAnswers = Array.from(document.querySelectorAll("input[type='hidden']")).map(answer => answer.value.trim());

            let isValid = true;
            const invalidIndices = [];
            expectedAnswers.forEach((expectedAnswer, index) => {
                if (answers[index] !== expectedAnswer) {
                    isValid = false;
                    invalidIndices.push(index + 1);
                }
            });

            if (isValid) {
                const randomNumber = Math.floor(Math.random() * 1000000) + 1;
                document.body.style.backgroundImage = "url('../static/chem_lab_door_closing.jpg')";
                const closingKey = "Closing Key: " + randomNumber;
                alert(closingKey);
                document.getElementById("randomNumber").innerText = closingKey;
                document.getElementById("randomNumber").style.display = "block";
                document.getElementById("submitBtn").style.display = "none";
                const payloadkey = {
                    user_email: "{{ session['user'] }}",
                    closing_key: randomNumber
                };

                const url = "/save_user_key";
                fetch(url, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify(payloadkey)
                })
                .then(response => response.json())
                .then(data => console.log(data))
                .catch(error => console.error(error));


            } else {
                // Save user answers to Firebase
                const userAnswers = Array.from(questions).map(question => question.value.trim());
                const payload = {
                    user_email: "{{ session['user'] }}",
                    answers: userAnswers
                };

                const url = "/save_user_answers";
                fetch(url, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify(payload)
                })
                .then(response => response.json())
                .then(data => console.log(data))
                .catch(error => console.error(error));
                const errorMessage = "Incorrect answers for questions: " + invalidIndices.join(", ");
                alert(errorMessage);
            }
        });
    </script>

</body>
</html>

project/templates/login.html
 <!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h2>Login with School Email</h2>
    
    <div class="login-container">
        <form method="POST" action="{{ url_for('chemlab.login') }}">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
            
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
            
            <button type="submit" class="btn">Login</button>
        </form>
        
        <hr>

        <div class="oauth-providers">
            <h2>Login with Social Media</h2>
            <button class="btn google-login" onclick="window.location.href='{{ url_for('chemlab.google_login') }}'">
                <img src="{{ url_for('static', filename='google_logo.png') }}" alt="" height="30">
                Login with Google
            </button>
            <!--
            <button class="btn facebook-login" onclick="window.location.href='{{ url_for('chemlab.facebook_login') }}'">
                <img src="{{ url_for('static', filename='facebook_logo.png') }}" alt="" height="30">
                Login with Facebook
            </button>
            -->
            <button class="btn linkedin-login" onclick="window.location.href='{{ url_for('chemlab.linkedin_login') }}'">
                <img src="{{ url_for('static', filename='linkedin_logo.png') }}" alt="" height="30">
                Login with LinkedIn
            </button>
        </div>

        <h2 class="signup-heading">Don't have an account? <button class="btn signup" onclick="window.location.href='{{ url_for('chemlab.signup') }}'">Sign up now!</button></h2>
    </div>
</body>
</html>

project/templates/recipe.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">
    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/recipe1.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">
    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/recipe2.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">

    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/recipes1.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipes1_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipes1-detail-container">
    <div class="recipes1-title">
        {% block recipes1_title %}
        {% endblock %}
    </div>

    <div class="recipes1-description card-overlay">
        {% block recipes1_description %}
        {% endblock %}
    </div>

    <div class="recipes1-image">
        {% block recipes1_image %}
        {% endblock %}
    </div>

    <div class="recipes1-tips card-overlay">
        {% block recipes1_tips %}
        {% endblock %}
    </div>

    <div class="recipes1-ingredients card-overlay">
        {% block recipes1_ingredients %}
        {% endblock %}
    </div>

    <div class="recipes1-steps card-overlay">
        {% block recipes1_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h2>Create an Account</h2>

    <div class="signup-container">
        <form method="POST" action="{{ url_for('signup') }}">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="first_name" required>

            <label for="last_name">Last Name:</label>
            <input type="text" id="last_name" name="last_name" required>

            <label for="date_of_birth">Date of Birth:</label>
            <input type="date" id="date_of_birth" name="date_of_birth" required>

            <label for="country">Country:</label>
            <input type="text" id="country" name="country" required>

            <button type="submit" class="btn">Sign Up</button>
        </form>

        <div class="login-link">
            <span>Already have an account? </span>
            <a class="btn login" href="{{ url_for('login') }}">Log in</a>
        </div>
    </div>
</body>
</html>

project/templates/tweetpost.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blogpost_style.css') }}">
{% endblock %}

{% block content %}
<div class="blogpost-container card-overlay">
    <div class="blogpost__heading">
        {% block title %}
        {% endblock %}

        <h3>by Saju Mulakkal</h3>

        {% block date %}
        {% endblock %}
    </div>

    <div class="blogpost__image">
        {% block image %}
        {% endblock %}
    </div>

    <div class="blogpost__article">
        {% block article %}
        {% endblock %}
    </div>
</div>
{% endblock %}