project/recipes1/__init__.py
# recipes1/__init__.py
"""
The `recipes1` blueprint handles displaying recipes.
"""
from flask import Blueprint

recipes1_blueprint = Blueprint('recipes1', __name__, template_folder='templates')

# Import the routes module
from . import routes

# Rest of the code remains the same

project/recipes1/routes.py
# recipes1/routes.py

from . import recipes1_blueprint
from flask import render_template, abort

# Duplicate the recipe names from the original recipes module
breakfast_recipes1_names = ['pancakes', 'acai_bowl', 'honey_bran_muffins', 'breakfast_scramble',
                           'pumpkin_donuts', 'waffles', 'omelette', 'chocolate_donuts', 'oatmeal',
                           'morning_glory_muffins', 'blueberry_smoothie_bowl']
dinner_recipes1_names = ['steak_fajitas', 'ground_beef_tacos', 'pizza', 'sweet_fire_chicken', 'tri_tip',
                        'shredded_chicken', 'taquitos', 'red_lentil_chili']
baked_goods_recipes1_names = ['bagels', 'french_bread', 'pitas', 'irish_soda_bread', 'soft_rolls',
                             'pizza_dough', 'pitas2', 'banana_bread']
side_dishes_recipes1_names = ['sweet_potatoes', 'spanish_rice', 'jasmine_rice', 'fruit_salad']
dessert_recipes1_names = ['brownies', 'chocolate_chip_cookies', 'linzer_cookies', 'sugar_cookies',
                         'flourless_chocolate_cake']
drink_recipes1_names = ['berry_smoothie', 'chocolate_milk_shake', 'apple_cider_vinegar_drink']


@recipes1_blueprint.route('/recipes1/', endpoint='recipes1_index')
def recipes1_index():
    return render_template('recipes1/recipes1.html',
                           number_of_breakfast_recipes1=len(breakfast_recipes1_names),
                           number_of_dinner_recipes1=len(dinner_recipes1_names),
                           number_of_baked_goods_recipes1=len(baked_goods_recipes1_names),
                           number_of_side_dishes_recipes1=len(side_dishes_recipes1_names),
                           number_of_dessert_recipes1=len(dessert_recipes1_names),
                           number_of_drink_recipes1=len(drink_recipes1_names))


@recipes1_blueprint.route('/recipes1/breakfast1/', endpoint='breakfast_recipes1_index')
def breakfast_recipes1_index():
    return render_template('recipes1/breakfast.html')


@recipes1_blueprint.route('/recipes1/breakfast1/<recipes1_name>/', endpoint='breakfast_recipes1_detail')
def breakfast_recipes1_detail(recipes1_name):
    if recipes1_name not in breakfast_recipes1_names:
        abort(404)

    return render_template(f'recipes1/{recipes1_name}.html')


@recipes1_blueprint.route('/recipes1/dinner1/', endpoint='dinner_recipes1_index')
def dinner_recipes1_index():
    return render_template('recipes1/dinner.html')


@recipes1_blueprint.route('/recipes1/dinner1/<recipes1_name>/', endpoint='dinner_recipes1_detail')
def dinner_recipes1_detail(recipes1_name):
    if recipes1_name not in dinner_recipes1_names:
        abort(404)

    return render_template(f'recipes1/{recipes1_name}.html')


@recipes1_blueprint.route('/recipes1/baked_goods1/', endpoint='baked_goods_recipes1_index')
def baked_goods_recipes1_index():
    return render_template('recipes1/baked_goods.html')


@recipes1_blueprint.route('/recipes1/baked_goods1/<recipes1_name>/', endpoint='baked_goods_recipes1_detail')
def baked_goods_recipes1_detail(recipes1_name):
    if recipes1_name not in baked_goods_recipes1_names:
        abort(404)

    return render_template(f'recipes1/{recipes1_name}.html')


@recipes1_blueprint.route('/recipes1/side_dishes1/', endpoint='side_dishes_recipes1_index')
def side_dishes_recipes1_index():
    return render_template('recipes1/side_dishes.html')


@recipes1_blueprint.route('/recipes1/side_dishes1/<recipes1_name>/', endpoint='side_dishes_recipes1_detail')
def side_dishes_recipes1_detail(recipes1_name):
    if recipes1_name not in side_dishes_recipes1_names:
        abort(404)

    return render_template(f'recipes1/{recipes1_name}.html')


@recipes1_blueprint.route('/recipes1/dessert1/', endpoint='dessert_recipes1_index')
def dessert_recipes1_index():
    return render_template('recipes1/dessert.html')


@recipes1_blueprint.route('/recipes1/dessert1/<recipes1_name>/', endpoint='dessert_recipes1_detail')
def dessert_recipes1_detail(recipes1_name):
    if recipes1_name not in dessert_recipes1_names:
        abort(404)

    return render_template(f'recipes1/{recipes1_name}.html')


@recipes1_blueprint.route('/recipes1/drink1/', endpoint='drink_recipes1_index')
def drink_recipes1_index():
    return render_template('recipes1/drink.html')


@recipes1_blueprint.route('/recipes1/drink1/<recipes1_name>/', endpoint='drink_recipes1_detail')
def drink_recipes1_detail(recipes1_name):
    if recipes1_name not in drink_recipes1_names:
        abort(404)

    return render_template(f'recipes1/{recipes1_name}.html')

project/recipes1/templates/recipes1/baked_goods.html
{% extends "base.html" %}

{% block content %}
<div class="recipes1-container">

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='bagels') }}">
            <img
              src="{{ url_for('static', filename='img/bagels.jpg') }}"
              alt="Bagels"
              class="card__image" />
            <div class="card__body">
                <h2>Bagels</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='french_bread') }}">
            <img
              src="{{ url_for('static', filename='img/french_bread.jpg') }}"
              alt="French Bread"
              class="card__image" />
            <div class="card__body">
                <h2>French Bread</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='pitas') }}">
            <img
              src="{{ url_for('static', filename='img/pitas.jpg') }}"
              alt="Pitas"
              class="card__image" />
            <div class="card__body">
                <h2>Pitas (No Yeast)</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='irish_soda_bread') }}">
            <img
              src="{{ url_for('static', filename='img/irish_soda_bread.jpg') }}"
              alt="Irish Soda Bread"
              class="card__image" />
            <div class="card__body">
                <h2>Irish Soda Bread</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='soft_rolls') }}">
            <img
              src="{{ url_for('static', filename='img/soft_rolls.jpg') }}"
              alt="Soft Rolls"
              class="card__image" />
            <div class="card__body">
                <h2>Soft Rolls</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='pizza_dough') }}">
            <img
              src="{{ url_for('static', filename='img/pizza_dough.jpg') }}"
              alt="Pizza Dough"
              class="card__image" />
            <div class="card__body">
                <h2>Pizza Dough</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='pitas2') }}">
            <img
              src="{{ url_for('static', filename='img/pitas2.jpg') }}"
              alt="Pitas"
              class="card__image" />
            <div class="card__body">
                <h2>Pitas</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.baked_goods_recipes1_detail', recipes1_name='banana_bread') }}">
            <img
              src="{{ url_for('static', filename='img/banana_bread.jpg') }}"
              alt="Banana Bread"
              class="card__image" />
            <div class="card__body">
                <h2>Banana Bread</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>
</div>
{% endblock %}

project/recipes1/templates/recipes1/breakfast.html
{% extends "base.html" %}

{% block content %}
<div class="recipes1-container">

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='pancakes') }}">
            <img
              src="{{ url_for('static', filename='img/pancakes.jpg') }}"
              alt="Pancakes"
              class="card__image" />
            <div class="card__body">
                <h2>Pancakes</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='honey_bran_muffins') }}">
            <img
              src="{{ url_for('static', filename='img/honey_bran_muffins.jpg') }}"
              alt="Honey Bran Muffins"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-long">Honey Bran Muffins</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='acai_bowl') }}">
            <img
              src="{{ url_for('static', filename='img/acai_bowl.jpg') }}"
              alt="Acai Bowl"
              class="card__image" />
            <div class="card__body">
                <h2>Acai Bowl</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='breakfast_scramble') }}">
            <img
              src="{{ url_for('static', filename='img/breakfast_scramble.jpg') }}"
              alt="Breakfast Scramble"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-long">Breakfast Scramble</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='pumpkin_donuts') }}">
            <img
              src="{{ url_for('static', filename='img/pumpkin_donuts.jpg') }}"
              alt="Pumpkin Donuts"
              class="card__image" />
            <div class="card__body">
                <h2>Pumpkin Donuts</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='waffles') }}">
            <img
              src="{{ url_for('static', filename='img/waffles.jpg') }}"
              alt="Waffles"
              class="card__image" />
            <div class="card__body">
                <h2>Waffles</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='omelette') }}">
            <img
              src="{{ url_for('static', filename='img/omelette.jpg') }}"
              alt="Omelette"
              class="card__image" />
            <div class="card__body">
                <h2>Omelette</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='chocolate_donuts') }}">
            <img
              src="{{ url_for('static', filename='img/chocolate_donuts.jpg') }}"
              alt="Chocolate Donuts"
              class="card__image" />
            <div class="card__body">
                <h2>Chocolate Donuts</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='oatmeal') }}">
            <img
              src="{{ url_for('static', filename='img/oatmeal.jpg') }}"
              alt="Oatmeal"
              class="card__image" />
            <div class="card__body">
                <h2>Oatmeal</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='morning_glory_muffins') }}">
            <img
              src="{{ url_for('static', filename='img/morning_glory_muffins.jpg') }}"
              alt="Morning Glory Muffins"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-long">Morning Glory Muffins</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.breakfast_recipes1_detail', recipes1_name='blueberry_smoothie_bowl') }}">
            <img
              src="{{ url_for('static', filename='img/blueberry_smoothie_bowl.jpg') }}"
              alt="Blueberry Smoothie Bowl"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-long">Blueberry Smoothie Bowl</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes1/templates/recipes1/dessert.html
{% extends "base.html" %}

{% block content %}
<div class="recipes1-container">

    <div class="card">
        <a href="{{ url_for('recipes1.dessert_recipes1_detail', recipes1_name='brownies') }}">
            <img
              src="{{ url_for('static', filename='img/brownies.jpg') }}"
              alt="Brownies"
              class="card__image" />
            <div class="card__body">
                <h2>Brownies</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dessert_recipes1_detail', recipes1_name='chocolate_chip_cookies') }}">
            <img
              src="{{ url_for('static', filename='img/chocolate_chip_cookies.jpg') }}"
              alt="Chocolate Chip Cookies"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-long">Chocolate Chip Cookies</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dessert_recipes1_detail', recipes1_name='linzer_cookies') }}">
            <img
              src="{{ url_for('static', filename='img/linzer_cookies.jpg') }}"
              alt="Linzer Cookies"
              class="card__image" />
            <div class="card__body">
                <h2>Linzer Cookies</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dessert_recipes1_detail', recipes1_name='sugar_cookies') }}">
            <img
              src="{{ url_for('static', filename='img/sugar_cookies.jpg') }}"
              alt="Sugar Cookies"
              class="card__image" />
            <div class="card__body">
                <h2>Sugar Cookies</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dessert_recipes1_detail', recipes1_name='flourless_chocolate_cake') }}">
            <img
              src="{{ url_for('static', filename='img/flourless_chocolate_cake.jpg') }}"
              alt="Flourless Chocolate Cake"
              class="card__image" />
            <div class="card__body">
                <h2>Flourless Chocolate Cake</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>
</div>
{% endblock %}

project/recipes1/templates/recipes1/dinner.html
{% extends "base.html" %}

{% block content %}
<div class="recipes1-container">

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='steak_fajitas') }}">
            <img
              src="{{ url_for('static', filename='img/steak_fajitas.jpg') }}"
              alt="Steak Fajitas"
              class="card__image" />
            <div class="card__body">
                <h2>Steak Fajitas</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='ground_beef_tacos') }}">
            <img
              src="{{ url_for('static', filename='img/ground_beef_tacos.jpg') }}"
              alt="Ground Beef Tacos"
              class="card__image" />
            <div class="card__body">
                <h2>Ground Beef Tacos</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='pizza') }}">
            <img
              src="{{ url_for('static', filename='img/pizza.jpg') }}"
              alt="Pizza"
              class="card__image" />
            <div class="card__body">
                <h2>Pizza</h2>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='sweet_fire_chicken') }}">
            <img
              src="{{ url_for('static', filename='img/sweet_fire_chicken.jpg') }}"
              alt="Sweet Fire Chicken"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-long">Sweet Fire Chicken</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='tri_tip') }}">
            <img
              src="{{ url_for('static', filename='img/tri_tip.jpg') }}"
              alt="Tri-Tip"
              class="card__image" />
            <div class="card__body">
                <h2>Tri-Tip</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='shredded_chicken') }}">
            <img
              src="{{ url_for('static', filename='img/shredded_chicken.jpg') }}"
              alt="Shredded Chicken"
              class="card__image" />
            <div class="card__body">
                <h2>Shredded Chicken</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='taquitos') }}">
            <img
              src="{{ url_for('static', filename='img/taquitos.jpg') }}"
              alt="Taquitos"
              class="card__image" />
            <div class="card__body">
                <h2>Taquitos</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.dinner_recipes1_detail', recipes1_name='red_lentil_chili') }}">
            <img
              src="{{ url_for('static', filename='img/red_lentil_chili.jpg') }}"
              alt="Red Lentil Chili"
              class="card__image" />
            <div class="card__body">
                <h2>Red Lentil Chili</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes1/templates/recipes1/drink.html
{% extends "base.html" %}

{% block content %}
<div class="recipes1-container">

    <div class="card">
        <a href="{{ url_for('recipes1.drink_recipes1_detail', recipes1_name='berry_smoothie') }}">
            <img
              src="{{ url_for('static', filename='img/berry_smoothie.jpg') }}"
              alt="Berry Smoothie"
              class="card__image" />
            <div class="card__body">
                <h2>Berry Smoothie</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.drink_recipes1_detail', recipes1_name='chocolate_milk_shake') }}">
            <img
              src="{{ url_for('static', filename='img/chocolate_milk_shake.jpg') }}"
              alt="Chocolate Milk Shake"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-long">Chocolate Milk Shake</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.drink_recipes1_detail', recipes1_name='apple_cider_vinegar_drink') }}">
            <img
              src="{{ url_for('static', filename='img/apple_cider_vinegar_drink.jpg') }}"
              alt="Apple Cider Vinegar Drink"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipes1-title-extra-long">Apple Cider Vinegar Drink</h2>
                <p class="recipes1-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipes1-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes1/templates/recipes1/side_dishes.html
{% extends "base.html" %}

{% block content %}
<div class="recipes1-container">

    <div class="card">
        <a href="{{ url_for('recipes1.side_dishes_recipes1_detail', recipes1_name='sweet_potatoes') }}">
            <img
              src="{{ url_for('static', filename='img/sweet_potatoes.jpg') }}"
              alt="Sweet Potatoes"
              class="card__image" />
            <div class="card__body">
                <h2>Sweet Potatoes</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.side_dishes_recipes1_detail', recipes1_name='spanish_rice') }}">
            <img
              src="{{ url_for('static', filename='img/spanish_rice.jpg') }}"
              alt="Spanish Rice"
              class="card__image" />
            <div class="card__body">
                <h2>Spanish Rice</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.side_dishes_recipes1_detail', recipes1_name='jasmine_rice') }}">
            <img
              src="{{ url_for('static', filename='img/jasmine_rice.jpg') }}"
              alt="Jasmine Rice"
              class="card__image" />
            <div class="card__body">
                <h2>Jasmine Rice</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes1.side_dishes_recipes1_detail', recipes1_name='fruit_salad') }}">
            <img
              src="{{ url_for('static', filename='img/fruit_salad.jpg') }}"
              alt="Fruit Salad"
              class="card__image" />
            <div class="card__body">
                <h2>Fruit Salad</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}